### ISSUE TITLE
Combining Now as template/interpolation for HTTPget.

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#159]
**Hi Akram**

I have a task, where I should call a HTTPget request with a URL+date like, 
 HttpGet: www.google.com//datecall-2019-11-21

Is it posible to use some kind of template/interpolation in the HTTPget-URL like: 
`<Setting name="url" value="https://www.google.com/datecall-{#1}" />`

Can it be solved otherwise with variables or is this a feature request ?

https://github.com/aelassas/Wexflow/wiki/Now
https://github.com/aelassas/Wexflow/wiki/HttpGet

Example #1 - with template
```
<Workflow xmlns="urn:wexflow-schema" id="99" name="HTTPget_Now" description="HTTPget_Now">
  <Settings>
    <Setting name="launchType" value="periodic" />
	<Setting name="period" value="1.00:00:00" />
  </Settings>
  <Tasks>
    <Task id="1" name="Now" description="Getting current day" enabled="true">
      <Setting name="culture" value="en-US" />  
      <Setting name="format" value="dd-MM-yyyy" />
      <Setting name="enabled" value="true" />
    </Task>
    <Task id="2" name="HttpGet" description="Executing GET request" enabled="true">
	  <Setting name="url" value="https://www.google.com/datecall-{#1}" />
    </Task>
    <Task id="3" name="FilesMover" description="Moving response file to HttpGet folder" enabled="true">
      <Setting name="selectFiles" value="2" />
      <Setting name="destFolder" value="C:\WexflowTesting\HttpGet\" />
      <Setting name="overwrite" value="true" />
    </Task>
  </Tasks>
</Workflow>
```
Example #2 - with local variables
```
<Workflow xmlns="urn:wexflow-schema" id="99" name="HTTPget_Now" description="HTTPget_Now">
  <Settings>
    <Setting name="launchType" value="periodic" />
	<Setting name="period" value="1.00:00:00" />
  </Settings>
  <Tasks>
    <Task id="1" name="Now" description="Getting current day" enabled="true">
      <Setting name="culture" value="en-US" />  
      <Variable name="myFormatedDate" value="dd-MM-yyyy" />
      <Setting name="enabled" value="true" />
    </Task>
    <Task id="2" name="HttpGet" description="Executing GET request" enabled="true">
	  <Setting name="url" value="https://www.google.com/datecall-{$myFormatedDate}" />
    </Task>
    <Task id="3" name="FilesMover" description="Moving response file to HttpGet folder" enabled="true">
      <Setting name="selectFiles" value="2" />
      <Setting name="destFolder" value="C:\WexflowTesting\HttpGet\" />
      <Setting name="overwrite" value="true" />
    </Task>
  </Tasks>
</Workflow>
```

**Comment by aelassas** [comment]
@janborup Yes, you can use local variables as follows:

```xml
<Workflow xmlns="urn:wexflow-schema" id="99" name="HTTPget_Now" description="HTTPget_Now">
  <Settings>
    <Setting name="launchType" value="periodic" />
	<Setting name="period" value="1.00:00:00" />
  </Settings>
  <LocalVariables>
    <Variable name="myFormatedDate" value="dd-MM-yyyy" />
  </LocalVariables>
  <Tasks>
    <Task id="1" name="Now" description="Getting current day" enabled="true">
      <Setting name="culture" value="en-US" />  
      <Setting name="format" value="$myFormatedDate" />
      <Setting name="enabled" value="true" />
    </Task>
    <Task id="2" name="HttpGet" description="Executing GET request" enabled="true">
	<Setting name="url" value="https://www.google.com/datecall-$myFormatedDate" />
    </Task>
    <Task id="3" name="FilesMover" description="Moving response file to HttpGet folder" enabled="true">
      <Setting name="selectFiles" value="2" />
      <Setting name="destFolder" value="C:\WexflowTesting\HttpGet\" />
      <Setting name="overwrite" value="true" />
    </Task>
  </Tasks>
</Workflow>
```

**Comment by janborup** [comment]
Hi Akram

Thanks for det the help, but your solution with variable It did not work. :-(

The HTTPget calls : **https://www.google.com/datecall-yyyy-MM-dd** and not the  **https://www.google.com/datecall-2019-11-21**

```
2019-11-21 22:59:54,186  INFO [5] - [Dealer Zone / 3] Workflow started.
2019-11-21 22:59:54,188  INFO [5] - [Dealer Zone / 3] [Now] Getting current date...
2019-11-21 22:59:54,189  INFO [5] - [Dealer Zone / 3] [Now] The value is: 2019-11-21
2019-11-21 22:59:54,189  INFO [5] - [Dealer Zone / 3] [Now] Task finished.
2019-11-21 22:59:54,189  INFO [5] - [Dealer Zone / 3] [HttpGet] Executing GET request...
2019-11-21 22:59:54,536 ERROR [5] - [Dealer Zone / 3] [HttpGet] An error occured while executing the GET request https://www.google.com/datecall-yyyy-MM-dd: The remote server returned an error: (404) Not Found.
2019-11-21 22:59:54,536  INFO [5] - [Dealer Zone / 3] [HttpGet] Task finished.
2019-11-21 22:59:54,536  INFO [5] - [Dealer Zone / 3] [FilesMover] Moving files...
2019-11-21 22:59:54,536  INFO [5] - [Dealer Zone / 3] [FilesMover] Task finished.
2019-11-21 22:59:54,552  INFO [5] - [Dealer Zone / 3] Workflow finished.
```
Any other solutions ?

**Comment by aelassas** [comment]
I understand what you want to do but for the moment it is not possible to
assign values to local variables from tasks.

Le jeu. 21 nov. 2019 à 23:08, Jan Borup Coyle <notifications@github.com> a
écrit :

**Comment by janborup** [comment]
Thanks Akram.

I'm trying to look at at source code for implementing some kind in interpolation like the MS standard, but I cannot find where you do the LocalVariable replace for ex. $myFormatedDate.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

As I see it, it should be posible to insert a simple.
`var date = DateTime.Now;`

Then with a little interpolation magic, this would be posible.
```
    <Task id="2" name="HttpGet" description="Executing GET request" enabled="true">
	<Setting name="url" value="https://www.google.com/datecall-${date:yyyy-MM-dd}" />
    </Task>
```

Can you point me to the right place to do this ?

**Comment by janborup** [comment]
A little try:

```
            //
            // Parse local variables.
            //
            var res = string.Empty;
            using (StringReader sr = new StringReader(dest))
            using (StringWriter sw = new StringWriter())
            {
                string line;
                while ((line = sr.ReadLine()) != null)
                {
                    foreach (var variable in localVariablesParsed)
                    {
                        string pattern = @"{.*?}";
                        Match m = Regex.Match(line, pattern, RegexOptions.IgnoreCase);
                        if (m.Success)
                        {
                            var date = DateTime.Now;
                            var replaceValue = @m.Value;
                            var result = Regex.Replace(line, pattern, replaceValue);
                        }
                        line = line.Replace("$" + variable.Key, variable.Value);
                    }
                    sw.WriteLine(line);
                }
                res = sw.ToString();
            }
```

**Comment by janborup** [comment]
Got an error - compile/running the last GitHUB source, with my above change:

```
2019-11-22 01:36:14,314  INFO [1] - Workflow loaded: {id: 19, name: Workflow_Zip, enabled: True, launchType: Trigger}
2019-11-22 01:36:14,318 ERROR [1] - An error occured while scheduling the workflow :
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wexflow.Core.WexflowEngine.ScheduleWorkflow(Workflow wf) in C:\Work\WexFlow\Wexflow\src\dotnet-core\Wexflow.Core\WexflowEngine.cs:line 574
2019-11-22 01:36:14,383 ERROR [1] - An error occured while scheduling the workflow :
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wexflow.Core.WexflowEngine.ScheduleWorkflow(Workflow wf) in C:\Work\WexFlow\Wexflow\src\dotnet-core\Wexflow.Core\WexflowEngine.cs:line 574
```

I will look at it again tomorrow.

**Comment by aelassas** [comment]
With the latest version of the source code, you must update your database
in c:\Wexflow\Database. Take the latest database from
samples\dotnet\Wexflow\Database\Wexflow.db. And you must also update
c:\Wexflow\Workflow.xsd. Take the latest xsd from src\dotnet\Wexflow.Core.

Le ven. 22 nov. 2019 à 01:41, Jan Borup Coyle <notifications@github.com> a
écrit :

**Comment by janborup** [comment]
Now my date-interpolation is working with above code:
[A little try](https://github.com/aelassas/Wexflow/issues/159#issuecomment-557331537)

When I'm trying to use the .Net Core version, the Backend starts, byt the Designer throws an error clicking the designer.
**http://localhost:8000/wexflow/search?s=
Request Method: GET
Status Code: 500 Internal Server Error**

**Comment by aelassas** [comment]
For .net core you must update the database and Wexflow.xsd too. The db is
in samples\dotnet-core\windows\Wexflow\Database. You must update them in
c:\Wexflow-dotnet-core\.

Le ven. 22 nov. 2019 à 14:55, Jan Borup Coyle <notifications@github.com> a
écrit :

**Comment by janborup** [comment]
Copy the database and XSD/XML file works like a charm.
Thanks 🙏

**Comment by aelassas** [comment]
@janborup Great, I will test your feature and will let you know. I will add it in the v5.2. Thanks.

**Comment by janborup** [comment]
Thanks for the pull request implementation.
Testet in both Windows and .net Core in v.5.2, and work fine.
