### ISSUE TITLE
User Name and Password not Signing in for Windows

### ISSUE THREAD

**Issue by benjstern** [aelassas/Wexflow#190]
I've been testing out the software and it seems when installing Wexflow on Windows 10, it doesn't allow me to login with the default credentials shortly after installing and configuring the database.

While the wexflow.log file shows:
`2020-02-23 11:13:07,377  INFO [3] - `
`2020-02-23 11:13:07,389  INFO [3] - Starting Wexflow Engine`

i keep on getting a popup message of 
> "An error occurred during authentication"

What i have noticed was that the wexflow service wasn't running so when running it manually it would stop shortly after. When looking through the vent log i saw two line items of interest:

Faulting application name: Wexflow.Server.exe, version: 4.2.0.0, time stamp: 0x5de7ed7b
Faulting module name: KERNELBASE.dll, version: 10.0.18362.628, time stamp: 0xf96f12ee
Exception code: 0xe0434352
Fault offset: 0x000000000003a839
Faulting process id: 0x19fc
Faulting application start time: 0x01d5ea2cbcc98ed9
Faulting application path: C:\Program Files\Wexflow\Wexflow.Server.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 5bf15597-c776-4c6c-ba48-6047175d0243
Faulting package full name: 
Faulting package-relative application ID: 

and: 
Application: Wexflow.Server.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SqlClient.SqlException
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(System.Data.ProviderBase.DbConnectionPoolIdentity, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, System.Data.SqlClient.SqlConnectionString, System.Data.SqlClient.SessionData, System.Data.ProviderBase.DbConnectionPool, System.String, Boolean, System.Data.SqlClient.SqlAuthenticationProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(System.Data.Common.DbConnectionOptions, System.Data.Common.DbConnectionPoolKey, System.Object, System.Data.ProviderBase.DbConnectionPool, System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(System.Data.ProviderBase.DbConnectionPool, System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions, System.Data.Common.DbConnectionPoolKey, System.Data.Common.DbConnectionOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(System.Data.Common.DbConnection, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(System.Data.Common.DbConnection, UInt32, Boolean, Boolean, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal ByRef)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal ByRef)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal, System.Data.ProviderBase.DbConnectionInternal ByRef)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>)
   at System.Data.SqlClient.SqlConnection.TryOpen(System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>)
   at System.Data.SqlClient.SqlConnection.Open()
   at Wexflow.Core.SQLServer.Helper.CreateTableIfNotExists(System.String, System.String)
   at Wexflow.Core.SQLServer.Db..ctor(System.String)
   at Wexflow.Core.WexflowEngine..ctor(System.String)
   at Wexflow.Server.WexflowServer..cctor()

Exception Info: System.TypeInitializationException
   at Wexflow.Server.WexflowServer.StartThread()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Any thoughts or directions would be welcome.

**Comment by aelassas** [comment]
If you're using Sql Server you need to start the service as a user having the rights to access Sql Server.

**Comment by benjstern** [comment]
@aelassas  I was starting the service as the administrator of the machine. Windows 10 Pro

**Comment by benjstern** [comment]
Alternatively i was able to get it working with net core, without any changes so I'm not sure why the regular .net wasn't working.

Would changing the DB type affect this in any way?

**Comment by aelassas** [comment]
@benjstern Can I close this issue?
