### ISSUE TITLE
FileContentMatch with WorkflowFiles collection

### ISSUE THREAD

**Issue by janborup** [aelassas/Wexflow#204]
Hi @aelassas 

Is it possible to add a workflow file collection to the FileContentMatch.cs ?

`return new TaskStatus(Status.Success, success);`
I can see it's only returns one TaskStatus to the ExecutionGraph, but a have a scenario where to search in multible files in a folder for af Keyword in the files, and the have a IF-ELSE graph for each file.

Is that possible ? 

/Jan

**Comment by aelassas** [comment]
@janborup Ok, I will update the task in the v5.4 to search for multiple files or files in a folder.

**Comment by aelassas** [comment]
@janborup I added support for multiple files and folders in FileContentMatch. I will publish it in the v5.4.

**Comment by janborup** [comment]
Thanks for the enhancement.

I think I got a little lost in translations of my task, because the mission it not quite done yet.

As I wrote above, i need postman to watch a folder, and then move-files to different folders  depending on the content in the files.

Example Task:
Watch in c:\WexflowTesting\Watchfolder3\
-- Get a File from folder
-- If-FileContenctMatch = "abca" move file to c:\WexflowTesting\Watchfolder3\abca
-- If-FileContenctMatch = "abcb" move file to c:\WexflowTesting\Watchfolder3\abcb
-- Else move file to c:\WexflowTesting\Watchfolder3\other
Repeat next file

The FileContentMatch only returns ONE status for this task "Succes" or "NotFound", so the inspected files cannot we validated for the single file, and a what to do with it.

I have tied different approach, but cannot solve the in a workflow (even with the FileContentMatch enhancement) 

Any suggestions ?

**Comment by aelassas** [comment]
@janborup I updated the task to solve your issue. Now FilesContentMatch loads the file if the regex matches the content of the file.

Here is a sample workflow with your use case:

```xml
<Workflow xmlns="urn:wexflow-schema" id="999" name="Workflow_FileContentMatch3" description="Workflow_FileContentMatch3">
 <Settings>
  <Setting name="launchType" value="trigger" />
  <Setting name="enabled" value="true" />
  <Setting name="approval" value="false" />
  <Setting name="enableParallelJobs" value="true" />
 </Settings>
 <LocalVariables />
 <Tasks>
  <Task id="200" name="FileContentMatch" description="Checking file..." enabled="true">
   <Setting name="folder" value="C:\WexflowTesting\Watchfolder3" />
   <Setting name="pattern" value="(abca)" />
  </Task>
  <Task id="1" name="FilesMover" description="Moving files to abca folder" enabled="true">
   <Setting name="selectFiles" value="200" />
   <Setting name="destFolder" value="C:\WexflowTesting\Watchfolder3\abca" />
   <Setting name="overwrite" value="true" />
  </Task>
  <Task id="201" name="FileContentMatch" description="Checking file..." enabled="true">
   <Setting name="folder" value="C:\WexflowTesting\Watchfolder3" />
   <Setting name="pattern" value="(abcb)" />
  </Task>
  <Task id="2" name="FilesMover" description="Moving files to abca folder" enabled="true">
   <Setting name="selectFiles" value="201" />
   <Setting name="destFolder" value="C:\WexflowTesting\Watchfolder3\abcb" />
   <Setting name="overwrite" value="true" />
  </Task>
 </Tasks>
 <ExecutionGraph>
  <If id="100" parent="-1" if="200">
   <Do>
    <Task id="1">
     <Parent id="-1" />
    </Task>
   </Do>
  </If>
  <If id="101" parent="-1" if="201">
   <Do>
    <Task id="2">
     <Parent id="-1" />
    </Task>
   </Do>
  </If>
 </ExecutionGraph>
</Workflow>
```

**Comment by janborup** [comment]
Great Thanks.

Have just testet the last code, with this change, but got an 'null Refrence Exception' error.

```
Now listening on: http://[::]:8000
Application started. Press Ctrl+C to shut down.
2020-04-06 21:47:59,492  INFO [14] - [Workflow_FileContentMatch3 / 1] Workflow started.
2020-04-06 21:47:59,495  INFO [14] - [Workflow_FileContentMatch3 / 1] [FileContentMatch] Checking file...
2020-04-06 21:47:59,496  INFO [14] - [Workflow_FileContentMatch3 / 1] [FileContentMatch] No content matching the pattern (abcb) was found in the file C:\WexflowTesting\Watchfolder3\file1.txt.
2020-04-06 21:47:59,499  INFO [14] - [Workflow_FileContentMatch3 / 1] [FileContentMatch] No content matching the pattern (abcb) was found in the file C:\WexflowTesting\Watchfolder3\file2.txt.
2020-04-06 21:47:59,500  INFO [14] - [Workflow_FileContentMatch3 / 1] [FileContentMatch] A content matching the pattern (abcb) was found in the file C:\WexflowTesting\Watchfolder3\file3.txt.
2020-04-06 21:47:59,500  INFO [14] - [Workflow_FileContentMatch3 / 1] [FileContentMatch] Task finished
2020-04-06 21:47:59,501 ERROR [14] - An error occured while running the workflow. Error: {id: 202, name: Workflow_FileContentMatch3, enabled: True, launchType: Trigger}
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wexflow.Core.Workflow.RunIf(Task[] tasks, Node[] nodes, If if, Boolean force, Boolean& success, Boolean& warning, Boolean& atLeastOneSucceed)
   at Wexflow.Core.Workflow.RunTasks(Node[] nodes, Task[] tasks, Boolean force)
   at Wexflow.Core.Workflow.<>c__DisplayClass183_0.<Start>b__0()

```

![image](https://user-images.githubusercontent.com/6866443/78599650-ccb01f80-7851-11ea-817c-9a7ddc0b54db.png)

I'm a missing something ?

**Comment by janborup** [comment]
Yep... the parent 100 fixed "not invoked" FileMover for the second TaskId:2, FileContentMatch 'abca', but the taskId:1 is still not invoked for the first FileContentMatch for the 'abcb' in file3.txt

```
2020-04-06 23:57:48.753 INFO - [Workflow_FileContentMatch3 / 1] Workflow started.
2020-04-06 23:57:48.755 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] Checking file...
2020-04-06 23:57:48.756 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] No content matching the pattern (abcb) was found in the file C:\WexflowTesting\Watchfolder3\file1.txt.
2020-04-06 23:57:48.758 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] No content matching the pattern (abcb) was found in the file C:\WexflowTesting\Watchfolder3\file2.txt.
2020-04-06 23:57:48.760 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] A content matching the pattern (abcb) was found in the file C:\WexflowTesting\Watchfolder3\file3.txt.
2020-04-06 23:57:48.762 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] Task finished
2020-04-06 23:57:48.763 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] Checking file...
2020-04-06 23:57:48.764 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] A content matching the pattern (abca) was found in the file C:\WexflowTesting\Watchfolder3\file1.txt.
2020-04-06 23:57:48.765 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] A content matching the pattern (abca) was found in the file C:\WexflowTesting\Watchfolder3\file2.txt.
2020-04-06 23:57:48.766 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] A content matching the pattern (abca) was found in the file C:\WexflowTesting\Watchfolder3\file3.txt.
2020-04-06 23:57:48.766 INFO - [Workflow_FileContentMatch3 / 1] [FileContentMatch] Task finished
2020-04-06 23:57:48.767 INFO - [Workflow_FileContentMatch3 / 1] [FilesMover] Moving files...
2020-04-06 23:57:48.767 INFO - [Workflow_FileContentMatch3 / 1] [FilesMover] Creating directory: C:\WexflowTesting\Watchfolder3\abca
2020-04-06 23:57:48.768 INFO - [Workflow_FileContentMatch3 / 1] [FilesMover] File moved: C:\WexflowTesting\Watchfolder3\file3.txt -> C:\WexflowTesting\Watchfolder3\abca\file3.txt
2020-04-06 23:57:48.769 INFO - [Workflow_FileContentMatch3 / 1] [FilesMover] File moved: C:\WexflowTesting\Watchfolder3\file2.txt -> C:\WexflowTesting\Watchfolder3\abca\file2.txt
2020-04-06 23:57:48.770 INFO - [Workflow_FileContentMatch3 / 1] [FilesMover] File moved: C:\WexflowTesting\Watchfolder3\file1.txt -> C:\WexflowTesting\Watchfolder3\abca\file1.txt
2020-04-06 23:57:48.771 INFO - [Workflow_FileContentMatch3 / 1] [FilesMover] Task finished.
2020-04-06 23:57:48.771 INFO - [Workflow_FileContentMatch3 / 1] Workflow finished.
```

What i'm i missing.

**Comment by janborup** [comment]
Have just found out that ALL files in a folder checked with FileContentMatch has to have a match before the Success is invoked, and thats why taskId 2 is fired, because all files contains 'abca'.

If I create at file4.txt with the content "You find nothing here", none of the Success (Task 1 or 2) is fired.

**Comment by aelassas** [comment]
@janborup Thanks for the pull request. Did you get it working for your use case?

**Comment by janborup** [comment]
Yes - thanks @aelassas 
The success fix solve the case, and it works fine.
