### ISSUE TITLE
Wexflow core version is throwing "Invalid culture" error while run the app.

### ISSUE THREAD

**Issue by srinathgnath** [aelassas/Wexflow#207]
Wexflow core version is throwing "Invalid culture" error while launching the app using run.bat file.

**Comment by aelassas** [comment]
Can you post the stack trace and details about the error?

**Comment by srinathgnath** [comment]
I'm using .Netframework version now (https://github.com/aelassas/Wexflow/releases/download/v5.3/wexflow-5.3-windows-x64.exe), Just got the below logs from eventlogs:

Application: Wexflow.Server.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Globalization.CultureNotFoundException
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at LiteDB.LCID.GetCulture(Int32)
   at LiteDB.Collation..ctor(Int32, System.Globalization.CompareOptions)
   at LiteDB.Engine.EnginePragmas.<.ctor>b__36_7(LiteDB.BufferSlice)
   at LiteDB.Engine.EnginePragmas..ctor(LiteDB.BufferSlice, LiteDB.Engine.HeaderPage)
   at LiteDB.Engine.HeaderPage.LoadPage()
   at LiteDB.Engine.LiteEngine..ctor(LiteDB.Engine.EngineSettings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(LiteDB.ConnectionString, LiteDB.BsonMapper)
   at Wexflow.Core.LiteDB.Db..ctor(System.String)
   at Wexflow.Core.WexflowEngine..ctor(System.String)
   at Wexflow.Server.WexflowServer..cctor()

Exception Info: System.TypeInitializationException
   at Wexflow.Server.WexflowServer.StartThread()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by aelassas** [comment]
@srinathgnath The problem is related to the database system. Just use another [database](https://github.com/aelassas/Wexflow/wiki/Databases) for the moment and it should be fine. Try [MongoDB](https://github.com/aelassas/Wexflow/wiki/MongoDB) for example.

Are you using Windows 10?

Also, what is your culture? Try [Get-Culture](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-culture?view=powershell-7) command on powershell.

**Comment by srinathgnath** [comment]
I'm using windows 7. System culture:
![image](https://user-images.githubusercontent.com/35440448/78698637-9f568680-78d0-11ea-89e5-747c27c5c5ca.png)

**Comment by aelassas** [comment]
@srinathgnath Ok thanks. Did you try MongoDB or another database system different from LiteDB?

**Comment by aelassas** [comment]
@srinathgnath Can you go to C:\Wexflow\Database, compress that folder and send me the .zip to akram.elassas@gmail.com please. So I can figure out what's the problem with your database.

**Comment by srinathgnath** [comment]
Sent. Check your mailbox.

**Comment by aelassas** [comment]
@srinathgnath Thanks. I've connected my dev environment to the db you sent me but couldn't reproduce the issue. It worked fine. However, I opened an [issue](https://github.com/mbdavid/LiteDB/issues/1619) on LiteDB repo. I am using Windows 10. Maybe that's why I couldn't reproduce it.

Can you download [LiteDB studio](https://github.com/mbdavid/LiteDB.Studio/releases), and open your database with it and see if it works please.

**Comment by aelassas** [comment]
@srinathgnath I found the bug. It is related to the collation of the database. Can you try with the following database please?  Just copy the new Wexflow.db in C:\Wexflow\Database and tell me if it works.

[Wexflow.zip](https://github.com/aelassas/Wexflow/files/4446523/Wexflow.zip)

**Comment by srinathgnath** [comment]
I changed db to sqllite and its working fine.

**Comment by aelassas** [comment]
@srinathgnath Thanks. Can you switch back to LiteDB and test with the database file that I sent you please? I need you to this so I can fix the collation bug please.

**Comment by srinathgnath** [comment]
yes, LiteDB also works fine now. Thanks

**Comment by aelassas** [comment]
@srinathgnath Thanks! If you want to use the  .net core version on Windows, here is the database file you need to copy in C:\Wexflow-dotnet-core\Database

[Wexflow.zip](https://github.com/aelassas/Wexflow/files/4446607/Wexflow.zip)
