### ISSUE TITLE
Custom plugin

### ISSUE THREAD

**Issue by teunlielu** [aelassas/Wexflow#289]
code:

using System.Threading;
using System.Xml.Linq;
using Wexflow.Core;

`namespace WexflowPlugin2
{
    public class MyTask : Task
    {
        public MyTask(XElement xe, Workflow wf) : base(xe, wf)
        {
            // Task settings go here
        }

        public override TaskStatus Run()
        {
            // Task logic goes here
            return new TaskStatus(Status.Success);
        }
    }
}`

<Workflow xmlns="urn:wexflow-schema" id="175" name="test" description="test">
	<Settings>
		<Setting name="launchType" value="trigger" />
		<Setting name="enabled" value="true" />
		<Setting name="approval" value="false" />
		<Setting name="enableParallelJobs" value="true" />
	</Settings>
	<LocalVariables />
	<Tasks>
		<Task id="1" name="MyTask" description="" enabled="true">
			<Setting name="url" value="google.nl" />
		</Task>
	</Tasks>
</Workflow>

dll copy to C:\Wexflow-netcore\Tasks
	"MyTask": [ {"Name": "url", "Required": true, "Type": "string", "List": [], "DefaultValue": ""} ] in TasksSetting. dll
	{"Name":  "MyTask", "Description": "WexflowPlugin test"} in Tasknamens.dll

**System.Exception: The type of the task MyTask could not be loaded.
   at Wexflow.Core.Workflow.Load(String xml) in D:\dev\Wexflow\src\src\netcore\Wexflow.Core\Workflow.cs:line 566
   at Wexflow.Core.Workflow..ctor(WexflowEngine wexflowEngine, Int32 jobId, Dictionary`2 jobs, String dbId, String xml, String wexflowTempFolder, String tasksFolder, String approvalFolder, String xsdPath, Db database, Variable[] globalVariables) in D:\dev\Wexflow\src\src\netcore\Wexflow.Core\Workflow.cs:line 286
   at Wexflow.Core.WexflowEngine.SaveWorkflow(String userId, UserProfile userProfile, String xml, Boolean schedule) in D:\dev\Wexflow\src\src\netcore\Wexflow.Core\WexflowEngine.cs:line 472**

what am I doing wrong?
Al program in .net core 3.1

**Comment by aelassas** [comment]
Your namespace should be Wexflow.Tasks.MyTask and the dll filename should be Wexflow.Tasks.MyTask.dll.

**Comment by teunlielu** [comment]
thanks
